### ISSUE TITLE
Week 5 Review Ticket - Chris Hom

### ISSUE THREAD

**Issue by Chom642** [AkhilNandhakumar/Guython#34]
> ## Total Score 4.8/5  -  Graded by Colin Howard
>
> ## Team Score 3/3
>
> ## Individual Score 1.8/2
[Create Task](https://scratch.mit.edu/projects/639956612)

**Comment by KoolKidKai** [comment]
Total Score /5 - Graded by Colin Howard

Team Score /3

- [ ] Hack #1; Phone number to sign up/authorization
- [ ] Hack #2; Logout in CRUD screen
- [ ] Hack #3; Login required in another portion of project

Individual /2

- [ ] Create task  coding requirements
- [ ] Runtime w/ comments on replit/intellij
